import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AppLanguage = "ar" | "en";
export const LANGUAGE_STORAGE_KEY = "amic:language";

const dictionary = {
  ar: { marketPulse: "نبضة السوق", alertCenter: "مركز التنبيهات", technicalAnalysis: "تحليل فني", confluence: "توافق الأطر", calendar: "التقويم الاقتصادي", backtest: "اختبار الاستراتيجيات", replay: "إعادة تشغيل السوق", scanner: "ماسح السوق", paperTrading: "التداول الورقي", tradeReview: "نقد الصفقات", leaderboard: "لوحة الصدارة", signals: "الإشارات المحفوظة", assistant: "مساعد AMIC", admin: "مركز الإدارة", workspace: "مساحة العمل", marketWorkspace: "السوق والتحليل", practiceWorkspace: "المحاكاة والمتابعة", toolsWorkspace: "أدوات إضافية", controlWorkspace: "الإدارة", responsibleReading: "قراءة مسؤولة", disclaimer: "المعلومات تحليلية وتعليمية، وليست توصية استثمارية.", logout: "تسجيل الخروج", toggleNavigation: "طي القائمة", openNavigation: "فتح التنقل", user: "مستخدم AMIC", language: "English", calendarEyebrow: "التقويم الاقتصادي الرسمي", calendarTitle: "التقويم الاقتصادي", calendarDescription: "أحداث أميركية عالية الأثر من جهات رسمية مفتوحة، بلا مفاتيح تجارية أو بطاقة دفع. التغطية الحالية ليست تقويمًا تجاريًا عالميًا شاملاً.", calendarUpcoming: "الأحداث القادمة", calendarCoverageLoading: "جارٍ جلب التغطية الرسمية…", calendarLoading: "جارٍ جلب الجدول الرسمي…", calendarError: "تعذّر الوصول إلى المصادر الرسمية الآن. جرّب التحديث لاحقًا.", calendarNoEvents: "لا توجد أحداث مستقبلية متاحة من المصادر الرسمية الآن.", calendarHigh: "عالي الأثر", calendarMedium: "متوسط الأثر", calendarSource: "المصدر الرسمي", calendarTelegramTitle: "تنبيه تيليغرام اختياري", calendarTelegramDescription: "يرسل النظام تذكيرًا قبل ساعة واحدة من أحداث BLS عالية الأثر ذات الوقت المعلن. لا يرسل تنبيهًا لموعد بلا ساعة رسمية.", calendarEnable: "تفعيل تنبيهات التقويم", calendarEnabled: "مفعّل", calendarDisabled: "غير مفعّل", calendarCountry: "الأحداث المدعومة: الولايات المتحدة.", calendarChatId: "معرّف محادثة تيليغرام", calendarBotReady: "بوت تيليغرام مهيأ في الخادم. احفظ المعرّف لتفعيل الاستلام.", calendarBotMissing: "بوت تيليغرام غير مهيأ في الخادم حاليًا.", calendarSave: "حفظ اشتراك التقويم", calendarSaveTelegram: "حفظ إعدادات تيليغرام" },
  en: { marketPulse: "Market Pulse", alertCenter: "Alert Center", technicalAnalysis: "Technical Analysis", confluence: "Multi-timeframe Confluence", calendar: "Economic Calendar", backtest: "Strategy Backtest", replay: "Market Replay", scanner: "Market Scanner", paperTrading: "Paper Trading", tradeReview: "Trade Review", leaderboard: "Leaderboard", signals: "Saved Signals", assistant: "AMIC Assistant", admin: "Admin Center", workspace: "Workspace", marketWorkspace: "Market & analysis", practiceWorkspace: "Practice & follow-up", toolsWorkspace: "More tools", controlWorkspace: "Administration", responsibleReading: "Responsible reading", disclaimer: "Information is analytical and educational, not investment advice.", logout: "Log out", toggleNavigation: "Collapse navigation", openNavigation: "Open navigation", user: "AMIC user", language: "العربية", calendarEyebrow: "OFFICIAL ECONOMIC CALENDAR", calendarTitle: "Economic calendar", calendarDescription: "High-impact U.S. events from open official sources, with no commercial key or payment card. Current coverage is not a full global commercial calendar.", calendarUpcoming: "Upcoming events", calendarCoverageLoading: "Loading official coverage…", calendarLoading: "Loading the official calendar…", calendarError: "Official sources are unavailable right now. Please try again later.", calendarNoEvents: "No upcoming events are available from official sources right now.", calendarHigh: "High impact", calendarMedium: "Medium impact", calendarSource: "Official source", calendarTelegramTitle: "Optional Telegram alert", calendarTelegramDescription: "The system sends a reminder one hour before supported high-impact BLS events with an announced time. It does not alert for events with no official time.", calendarEnable: "Enable calendar alerts", calendarEnabled: "Enabled", calendarDisabled: "Disabled", calendarCountry: "Supported events: United States.", calendarChatId: "Telegram chat ID", calendarBotReady: "The Telegram bot is configured on the server. Save your chat ID to receive alerts.", calendarBotMissing: "The Telegram bot is not currently configured on the server.", calendarSave: "Save calendar subscription", calendarSaveTelegram: "Save Telegram settings" },
} as const;

export type TranslationKey = keyof typeof dictionary.ar;
export function getStoredLanguage(value?: string | null): AppLanguage { return value === "en" ? "en" : "ar"; }
export function translate(language: AppLanguage, key: TranslationKey) { return dictionary[language][key]; }

const I18nContext = createContext<{ language: AppLanguage; setLanguage: (language: AppLanguage) => void; t: (key: TranslationKey) => string } | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<AppLanguage>(() => getStoredLanguage(typeof window === "undefined" ? null : window.localStorage.getItem(LANGUAGE_STORAGE_KEY)));
  useEffect(() => { window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language); document.documentElement.lang = language; document.documentElement.dir = language === "ar" ? "rtl" : "ltr"; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translate(language, key) }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error("useI18n must be used inside LanguageProvider"); return value; }
