import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeading, Panel } from "@/components/market-ui";
import { trpc } from "@/lib/trpc";
import { EyeOff, Medal, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Leaderboard() {
  const utils = trpc.useUtils();
  const entries = trpc.leaderboard.list.useQuery();
  const profile = trpc.leaderboard.profile.get.useQuery();
  const [enabled, setEnabled] = useState(false); const [displayName, setDisplayName] = useState("متداول AMIC"); const [anonymized, setAnonymized] = useState(true);
  useEffect(() => { if (profile.data) { setEnabled(profile.data.enabled); setDisplayName(profile.data.displayName); setAnonymized(profile.data.anonymized); } }, [profile.data]);
  const save = trpc.leaderboard.profile.save.useMutation({ onSuccess: () => { toast.success("حُفظت تفضيلات لوحة الصدارة."); utils.leaderboard.list.invalidate(); utils.leaderboard.profile.get.invalidate(); }, onError: error => toast.error(error.message) });
  return <><PageHeading eyebrow="OPT-IN PAPER TRADING" title="لوحة الصدارة" description="مقارنة تعليمية مبنية على الصفقات الورقية المغلقة فقط. الاشتراك اختياري تمامًا ولا تظهر رسائل البريد أو بيانات الحساب." />
    <div className="grid gap-4 xl:grid-cols-[330px_1fr]"><Panel><Trophy className="size-5 text-primary" /><h2 className="mt-3 text-lg font-semibold">مشاركة اختيارية</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">فعّل المشاركة لعرض المقاييس المجمعة لصفقاتك الورقية. يمكنك استخدام اسم عرض أو إخفاءه باسم «متداول مجهول» في أي وقت.</p><div className="mt-5 flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.025] p-3"><span className="text-sm">المشاركة في الصدارة</span><Button size="sm" variant={enabled ? "default" : "outline"} onClick={() => setEnabled(value => !value)}>{enabled ? "مفعّلة" : "غير مفعّلة"}</Button></div><div className="mt-4"><Label>اسم العرض</Label><Input className="mt-2 bg-white/[0.025]" value={displayName} onChange={event => setDisplayName(event.target.value)} disabled={anonymized} maxLength={40} /></div><div className="mt-4 flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.025] p-3"><div><p className="text-sm">إخفاء الاسم</p><p className="mt-1 text-xs text-muted-foreground">يعرض «متداول مجهول» بدل اسم العرض.</p></div><Button size="sm" variant={anonymized ? "default" : "outline"} onClick={() => setAnonymized(value => !value)}><EyeOff className="ml-1 size-3.5" />{anonymized ? "مفعّل" : "غير مفعّل"}</Button></div><Button className="mt-5 w-full" disabled={save.isPending} onClick={() => save.mutate({ enabled, displayName: displayName.trim() || "متداول AMIC", anonymized })}>حفظ الخصوصية والمشاركة</Button></Panel>
      <Panel><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">ترتيب الصفقات الورقية</h2><p className="mt-1 text-xs text-muted-foreground">يُرتب بالعائد الإجمالي النسبي للصفقات المغلقة. لا يمثل دليلًا على أداء مستقبلي.</p></div><Medal className="size-5 text-primary" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-right text-sm"><thead className="border-b border-white/[0.08] text-xs text-muted-foreground"><tr><th className="pb-3">الترتيب</th><th className="pb-3">المتداول</th><th className="pb-3">الصفقات</th><th className="pb-3">نسبة الفوز</th><th className="pb-3">العائد</th><th className="pb-3">ر/خ محقق</th></tr></thead><tbody>{entries.data?.length ? entries.data.map((entry, index) => <tr className="border-b border-white/[0.05]" key={`${entry.displayName}-${index}`}><td className="py-3 font-mono">#{index + 1}</td><td className="py-3">{entry.displayName}</td><td className="py-3 font-mono">{entry.totalTrades}</td><td className="py-3 font-mono">{entry.winRate.toFixed(1)}%</td><td className={entry.totalReturnPercent >= 0 ? "py-3 font-mono text-emerald-300" : "py-3 font-mono text-rose-300"}>{entry.totalReturnPercent >= 0 ? "+" : ""}{entry.totalReturnPercent.toFixed(2)}%</td><td className={Number(entry.realizedPnl) >= 0 ? "py-3 font-mono text-emerald-300" : "py-3 font-mono text-rose-300"}>{entry.realizedPnl}</td></tr>) : <tr><td colSpan={6} className="py-12 text-center text-sm text-muted-foreground">لا توجد نتائج مشتركة بعد. تبقى كل الصفقات خاصة ما لم يختر مالكها المشاركة.</td></tr>}</tbody></table></div></Panel></div></>;
}
