import { HistoricalReplayChart } from "@/components/HistoricalReplayChart";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeading, Panel } from "@/components/market-ui";
import { trpc } from "@/lib/trpc";
import { calculateConfluenceIct } from "@shared/confluenceIct";
import { getReplayVisibleCandles } from "@shared/replay";
import { ChevronLeft, ChevronRight, History, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

export default function Replay() {
  const [symbol, setSymbol] = useState("BTCUSDT"); const [exchange, setExchange] = useState("BINANCE"); const [interval, setInterval] = useState<"60m" | "4h" | "1d">("1d"); const [lastVisibleIndex, setLastVisibleIndex] = useState(-1);
  const candlesQuery = trpc.market.candles.useQuery({ symbol: symbol.trim().toUpperCase(), exchange: exchange.trim().toUpperCase(), interval, range: interval === "60m" ? "1mo" : interval === "4h" ? "3mo" : "6mo", limit: 500 }, { enabled: Boolean(symbol.trim() && exchange.trim()), refetchOnWindowFocus: false, staleTime: 5 * 60_000 });
  const historical = candlesQuery.data?.candles ?? [];
  useEffect(() => { if (historical.length) setLastVisibleIndex(Math.max(0, Math.min(historical.length - 1, Math.floor(historical.length * 0.45)))); }, [historical]);
  const visibleCandles = useMemo(() => getReplayVisibleCandles(historical, lastVisibleIndex), [historical, lastVisibleIndex]);
  const confluence = useMemo(() => calculateConfluenceIct(visibleCandles), [visibleCandles]);
  const current = visibleCandles.at(-1);
  const step = (direction: number) => setLastVisibleIndex(index => Math.max(0, Math.min(historical.length - 1, index + direction)));
  return <><PageHeading eyebrow="AMIC HISTORICAL REPLAY" title="إعادة تشغيل السوق" description="تقدم شمعة واحدة في كل مرة. تحسب المؤشرات وConfluence من الشموع المرئية فقط ولا تعرض أي شمعة مستقبلية." />
    <div className="grid gap-4 xl:grid-cols-[320px_1fr]"><Panel><History className="size-5 text-primary" /><h2 className="mt-3 text-lg font-semibold">إعداد الجلسة</h2><div className="mt-5 space-y-4"><div><Label>الرمز</Label><Input dir="ltr" className="mt-2 bg-white/[0.025]" value={symbol} onChange={event => setSymbol(event.target.value)} /></div><div><Label>البورصة</Label><Input dir="ltr" className="mt-2 bg-white/[0.025]" value={exchange} onChange={event => setExchange(event.target.value)} /></div><div><Label>الإطار</Label><select className="mt-2 h-10 w-full rounded-md border border-input bg-white/[0.025] px-3 text-sm" value={interval} onChange={event => setInterval(event.target.value as typeof interval)}><option className="bg-background" value="60m">1h</option><option className="bg-background" value="4h">4h</option><option className="bg-background" value="1d">1d</option></select></div></div><div className="mt-6 rounded-xl border border-primary/15 bg-primary/[0.04] p-3 text-xs leading-5 text-muted-foreground">تُخفى الشموع التالية من الرسم والحساب إلى أن تضغط «الشمعة التالية». لا تستخدم هذه الصفحة بثًا حيًا أو أي تنبؤ.</div></Panel>
      <div className="space-y-4">{candlesQuery.isLoading ? <Panel><p className="text-sm text-muted-foreground">جارٍ تجهيز التاريخ…</p></Panel> : candlesQuery.isError ? <Panel><p className="text-sm text-destructive">تعذّر جلب تاريخ الشموع لهذه الجلسة.</p></Panel> : historical.length ? <><Panel><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">{symbol.toUpperCase()} · {interval}</p><p className="mt-1 text-xs text-muted-foreground">الشمعة المرئية {visibleCandles.length} من {historical.length} · {current ? new Date(current.time * 1000).toLocaleString("ar") : "—"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setLastVisibleIndex(Math.max(0, Math.floor(historical.length * 0.45)))}><RotateCcw className="ml-1 size-4" />إعادة</Button><Button variant="outline" size="sm" disabled={lastVisibleIndex <= 0} onClick={() => step(-1)}><ChevronRight className="size-4" />سابق</Button><Button size="sm" disabled={lastVisibleIndex >= historical.length - 1} onClick={() => step(1)}>التالي<ChevronLeft className="mr-1 size-4" /></Button></div></div><HistoricalReplayChart candles={visibleCandles} /></Panel><div className="grid gap-3 md:grid-cols-3"><Panel><p className="text-xs text-muted-foreground">إشارة Confluence</p><p className="mt-2 text-xl font-semibold">{confluence.summary.signal}</p></Panel><Panel><p className="text-xs text-muted-foreground">الاتجاه</p><p className="mt-2 text-xl font-semibold">{confluence.summary.trend}</p></Panel><Panel><p className="text-xs text-muted-foreground">صافي Confluence</p><p className="mt-2 text-xl font-semibold" dir="ltr">{confluence.summary.confluence.net} / {confluence.summary.confluence.max}</p></Panel></div><Panel><p className="text-sm font-semibold">العوامل المرئية الآن</p><div className="mt-3 grid gap-2 md:grid-cols-2">{confluence.breakdown.length ? confluence.breakdown.map(item => <div key={item.id} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="flex justify-between gap-3"><span className="text-sm">{item.label}</span><span className="font-mono text-xs" dir="ltr">{item.points}/{item.maxPoints}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></div>) : <p className="text-sm text-muted-foreground">لا توجد عوامل مكتملة في النافذة المرئية بعد.</p>}</div></Panel></> : <Panel><p className="text-sm text-muted-foreground">لا توجد شموع متاحة لجلسة Replay هذه.</p></Panel>}</div></div></>;
}
